/* Generated by Yosys 0.42+2 (git sha1 82783646e, g++ 13.2.0-23ubuntu4 -fPIC -Os) */

module Booth_Radix_Table(In, Shift, Negation, Zero);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  input [2:0] In;
  wire [2:0] In;
  output Negation;
  wire Negation;
  output Shift;
  wire Shift;
  output Zero;
  wire Zero;
  assign Negation = In[2] & _01_;
  assign _00_ = In[1] & In[0];
  assign _01_ = ! _00_;
  assign _02_ = ! _03_;
  assign _03_ = In[1] | In[0];
  assign Zero = In[2] ? _00_ : _02_;
  assign Shift = In[2] ? _02_ : _00_;
endmodule
