/* Generated by Yosys 0.42+2 (git sha1 82783646e, g++ 13.2.0-23ubuntu4 -fPIC -Os) */

module Booth_Radix_Table(In, Shift, Negation, Zero);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  input [2:0] In;
  wire [2:0] In;
  output Negation;
  wire Negation;
  output Shift;
  wire Shift;
  output Zero;
  wire Zero;
  or2v0x05 _10_ (
    .a(_00_),
    .b(_01_),
    .z(_06_)
  );
  nd2v0x05 _11_ (
    .a(_00_),
    .b(_01_),
    .z(_07_)
  );
  mxi2v0x05 _12_ (
    .a0(_07_),
    .a1(_06_),
    .s(_02_),
    .z(_04_)
  );
  an2v0x05 _13_ (
    .a(_02_),
    .b(_07_),
    .z(_03_)
  );
  mxi2v0x05 _14_ (
    .a0(_06_),
    .a1(_07_),
    .s(_02_),
    .z(_05_)
  );
  assign _02_ = In[2];
  assign Shift = _04_;
  assign Negation = _03_;
  assign _00_ = In[0];
  assign _01_ = In[1];
  assign Zero = _05_;
endmodule
