/* Generated by Yosys 0.42+2 (git sha1 82783646e, g++ 13.2.0-23ubuntu4 -fPIC -Os) */

module Look_Ahead_Adder(a, b, s, cout, c0);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  input [3:0] a;
  wire [3:0] a;
  input [3:0] b;
  wire [3:0] b;
  input c0;
  wire c0;
  wire c4;
  output cout;
  wire cout;
  wire g0;
  wire g1;
  wire g2;
  wire g3;
  wire p0;
  wire p1;
  wire p2;
  wire p3;
  output [3:0] s;
  wire [3:0] s;
  iv1v0x05 _45_ (
    .a(_29_),
    .z(_31_)
  );
  an2v0x05 _46_ (
    .a(_37_),
    .b(_25_),
    .z(_32_)
  );
  aoi21v0x05 _47_ (
    .a1(_38_),
    .a2(_32_),
    .b(_28_),
    .z(_33_)
  );
  aoi21a2v0x05 _48_ (
    .a1(_39_),
    .a2(_33_),
    .b(_29_),
    .z(_34_)
  );
  oai21a2bv0x05 _49_ (
    .a1(_34_),
    .a2(_40_),
    .b(_30_),
    .z(_26_)
  );
  xor2v0x05 _50_ (
    .a(_37_),
    .b(_25_),
    .z(_41_)
  );
  oan21v0x05 _51_ (
    .a1(_27_),
    .a2(_32_),
    .b(_38_),
    .z(_35_)
  );
  xoon21v0x05 _52_ (
    .a1(_27_),
    .a2(_32_),
    .b(_38_),
    .z(_42_)
  );
  oai21v0x05 _53_ (
    .a1(_28_),
    .a2(_35_),
    .b(_39_),
    .z(_36_)
  );
  xoon21v0x05 _54_ (
    .a1(_28_),
    .a2(_35_),
    .b(_39_),
    .z(_43_)
  );
  xaoi21v0x05 _55_ (
    .a1(_31_),
    .a2(_36_),
    .b(_40_),
    .z(_44_)
  );
  ha X1 (
    .a(a[0]),
    .b(b[0]),
    .co(g0),
    .sum(p0)
  );
  ha X2 (
    .a(a[1]),
    .b(b[1]),
    .co(g1),
    .sum(p1)
  );
  ha X3 (
    .a(a[2]),
    .b(b[2]),
    .co(g2),
    .sum(p2)
  );
  ha X4 (
    .a(a[3]),
    .b(b[3]),
    .co(g3),
    .sum(p3)
  );
  assign c4 = cout;
  assign _40_ = p3;
  assign _29_ = g2;
  assign _30_ = g3;
  assign _39_ = p2;
  assign _28_ = g1;
  assign _37_ = p0;
  assign _38_ = p1;
  assign _25_ = c0;
  assign cout = _26_;
  assign s[0] = _41_;
  assign _27_ = g0;
  assign s[1] = _42_;
  assign s[2] = _43_;
  assign s[3] = _44_;
endmodule

module ha(a, b, sum, co);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  input a;
  wire a;
  input b;
  wire b;
  output co;
  wire co;
  output sum;
  wire sum;
  an2v0x05 _4_ (
    .a(_1_),
    .b(_0_),
    .z(_2_)
  );
  xor2v0x05 _5_ (
    .a(_1_),
    .b(_0_),
    .z(_3_)
  );
  assign _1_ = b;
  assign _0_ = a;
  assign sum = _3_;
  assign co = _2_;
endmodule
