/* Generated by Yosys 0.42+2 (git sha1 82783646e, g++ 13.2.0-23ubuntu4 -fPIC -Os) */

module Booth_Radix_Table(In, Shift, Negation, Zero);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  input [2:0] In;
  wire [2:0] In;
  output Negation;
  wire Negation;
  output Shift;
  wire Shift;
  output Zero;
  wire Zero;
  sky130_fd_sc_hd__clkinv_1 _11_ (
    .A(_02_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__or2_0 _12_ (
    .A(_00_),
    .B(_01_),
    .X(_07_)
  );
  sky130_fd_sc_hd__a21oi_1 _13_ (
    .A1(_00_),
    .A2(_01_),
    .B1(_02_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__a21oi_1 _14_ (
    .A1(_02_),
    .A2(_07_),
    .B1(_08_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__a21boi_0 _15_ (
    .A1(_00_),
    .A2(_01_),
    .B1_N(_02_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__a21oi_1 _16_ (
    .A1(_06_),
    .A2(_07_),
    .B1(_03_),
    .Y(_05_)
  );
  assign _02_ = In[2];
  assign Shift = _04_;
  assign Negation = _03_;
  assign _00_ = In[0];
  assign _01_ = In[1];
  assign Zero = _05_;
endmodule
