/* Generated by Yosys 0.42+2 (git sha1 82783646e, g++ 13.2.0-23ubuntu4 -fPIC -Os) */

module Booth_Radix_Table(In, Shift, Negation, Zero);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  input [2:0] In;
  wire [2:0] In;
  output Negation;
  wire Negation;
  output Shift;
  wire Shift;
  output Zero;
  wire Zero;
  sky130_fd_sc_hd__clkinv_1 _17_ (
    .A(_10_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__a21boi_0 _18_ (
    .A1(_09_),
    .A2(_08_),
    .B1_N(_10_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__or2_0 _19_ (
    .A(_09_),
    .B(_08_),
    .X(_16_)
  );
  sky130_fd_sc_hd__a21oi_1 _20_ (
    .A1(_15_),
    .A2(_16_),
    .B1(_11_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__a21oi_1 _21_ (
    .A1(_09_),
    .A2(_08_),
    .B1(_10_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__a21oi_1 _22_ (
    .A1(_10_),
    .A2(_16_),
    .B1(_14_),
    .Y(_12_)
  );
  assign _09_ = In[1];
  assign _10_ = In[2];
  assign _08_ = In[0];
  assign Zero = _13_;
  assign Shift = _12_;
  assign Negation = _11_;
endmodule
