/* Generated by Yosys 0.42+2 (git sha1 82783646e, g++ 13.2.0-23ubuntu4 -fPIC -Os) */

module Look_Ahead_Adder(a, b, s, cout, c0);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  input [3:0] a;
  wire [3:0] a;
  input [3:0] b;
  wire [3:0] b;
  input c0;
  wire c0;
  wire c4;
  output cout;
  wire cout;
  wire g0;
  wire g1;
  wire g2;
  wire g3;
  wire p0;
  wire p1;
  wire p2;
  wire p3;
  output [3:0] s;
  wire [3:0] s;
  sky130_fd_sc_hd__clkinv_1 _45_ (
    .A(_38_),
    .Y(_31_)
  );
  sky130_fd_sc_hd__a31o_1 _46_ (
    .A1(_37_),
    .A2(_38_),
    .A3(_25_),
    .B1(_28_),
    .X(_32_)
  );
  sky130_fd_sc_hd__a21o_1 _47_ (
    .A1(_39_),
    .A2(_32_),
    .B1(_29_),
    .X(_33_)
  );
  sky130_fd_sc_hd__a21o_1 _48_ (
    .A1(_40_),
    .A2(_33_),
    .B1(_30_),
    .X(_26_)
  );
  sky130_fd_sc_hd__xor2_1 _49_ (
    .A(_37_),
    .B(_25_),
    .X(_41_)
  );
  sky130_fd_sc_hd__a21oi_1 _50_ (
    .A1(_37_),
    .A2(_25_),
    .B1(_27_),
    .Y(_34_)
  );
  sky130_fd_sc_hd__xnor2_1 _51_ (
    .A(_38_),
    .B(_34_),
    .Y(_42_)
  );
  sky130_fd_sc_hd__o21bai_1 _52_ (
    .A1(_31_),
    .A2(_34_),
    .B1_N(_28_),
    .Y(_35_)
  );
  sky130_fd_sc_hd__xor2_1 _53_ (
    .A(_39_),
    .B(_35_),
    .X(_43_)
  );
  sky130_fd_sc_hd__a21oi_1 _54_ (
    .A1(_39_),
    .A2(_35_),
    .B1(_29_),
    .Y(_36_)
  );
  sky130_fd_sc_hd__xnor2_1 _55_ (
    .A(_40_),
    .B(_36_),
    .Y(_44_)
  );
  ha X1 (
    .a(a[0]),
    .b(b[0]),
    .co(g0),
    .sum(p0)
  );
  ha X2 (
    .a(a[1]),
    .b(b[1]),
    .co(g1),
    .sum(p1)
  );
  ha X3 (
    .a(a[2]),
    .b(b[2]),
    .co(g2),
    .sum(p2)
  );
  ha X4 (
    .a(a[3]),
    .b(b[3]),
    .co(g3),
    .sum(p3)
  );
  assign c4 = cout;
  assign _40_ = p3;
  assign _29_ = g2;
  assign _30_ = g3;
  assign _39_ = p2;
  assign _28_ = g1;
  assign _37_ = p0;
  assign _38_ = p1;
  assign _25_ = c0;
  assign cout = _26_;
  assign s[0] = _41_;
  assign _27_ = g0;
  assign s[1] = _42_;
  assign s[2] = _43_;
  assign s[3] = _44_;
endmodule

module ha(a, b, sum, co);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  input a;
  wire a;
  input b;
  wire b;
  output co;
  wire co;
  output sum;
  wire sum;
  sky130_fd_sc_hd__and2_0 _4_ (
    .A(_1_),
    .B(_0_),
    .X(_2_)
  );
  sky130_fd_sc_hd__xor2_1 _5_ (
    .A(_1_),
    .B(_0_),
    .X(_3_)
  );
  assign _1_ = b;
  assign _0_ = a;
  assign sum = _3_;
  assign co = _2_;
endmodule
