/* Generated by Yosys 0.42+2 (git sha1 82783646e, g++ 13.2.0-23ubuntu4 -fPIC -Os) */

module Multiplier_Sub_Module(Multiplicant, Shift, Negation, Zero, Result);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  input [7:0] Multiplicant;
  wire [7:0] Multiplicant;
  input Negation;
  wire Negation;
  output [8:0] Result;
  wire [8:0] Result;
  input Shift;
  wire Shift;
  input Zero;
  wire Zero;
  wire [1:0] sel;
  sky130_fd_sc_hd__clkinv_1 _137_ (
    .A(_077_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__clkinv_1 _138_ (
    .A(_081_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__clkinv_1 _139_ (
    .A(_083_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nor3b_1 _140_ (
    .A(_095_),
    .B(_094_),
    .C_N(_076_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__nor2_1 _141_ (
    .A(_084_),
    .B(_094_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__o21ai_0 _142_ (
    .A1(_084_),
    .A2(_094_),
    .B1(_076_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__o21ai_0 _143_ (
    .A1(_094_),
    .A2(_096_),
    .B1(_100_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__nor2b_1 _144_ (
    .A(_094_),
    .B_N(_084_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__a31oi_1 _145_ (
    .A1(_076_),
    .A2(_077_),
    .A3(_102_),
    .B1(_095_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__and2_0 _146_ (
    .A(_101_),
    .B(_103_),
    .X(_086_)
  );
  sky130_fd_sc_hd__nor3_1 _147_ (
    .A(_076_),
    .B(_077_),
    .C(_078_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__o21a_1 _148_ (
    .A1(_076_),
    .A2(_077_),
    .B1(_078_),
    .X(_105_)
  );
  sky130_fd_sc_hd__nor2_1 _149_ (
    .A(_104_),
    .B(_105_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__a21oi_1 _150_ (
    .A1(_094_),
    .A2(_096_),
    .B1(_084_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__and2_0 _151_ (
    .A(_084_),
    .B(_094_),
    .X(_108_)
  );
  sky130_fd_sc_hd__xor2_1 _152_ (
    .A(_076_),
    .B(_077_),
    .X(_109_)
  );
  sky130_fd_sc_hd__a221oi_1 _153_ (
    .A1(_102_),
    .A2(_106_),
    .B1(_108_),
    .B2(_109_),
    .C1(_107_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__nor3_1 _154_ (
    .A(_084_),
    .B(_094_),
    .C(_078_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__nor3_1 _155_ (
    .A(_095_),
    .B(_110_),
    .C(_111_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__or4_1 _156_ (
    .A(_076_),
    .B(_077_),
    .C(_078_),
    .D(_079_),
    .X(_112_)
  );
  sky130_fd_sc_hd__xnor2_1 _157_ (
    .A(_079_),
    .B(_104_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__nand2_1 _158_ (
    .A(_106_),
    .B(_108_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__nor2b_1 _159_ (
    .A(_084_),
    .B_N(_094_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__a222oi_1 _160_ (
    .A1(_079_),
    .A2(_099_),
    .B1(_102_),
    .B2(_113_),
    .C1(_115_),
    .C2(_078_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__a21oi_1 _161_ (
    .A1(_114_),
    .A2(_116_),
    .B1(_095_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__xor2_1 _162_ (
    .A(_080_),
    .B(_112_),
    .X(_117_)
  );
  sky130_fd_sc_hd__nand2_1 _163_ (
    .A(_108_),
    .B(_113_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__a222oi_1 _164_ (
    .A1(_080_),
    .A2(_099_),
    .B1(_102_),
    .B2(_117_),
    .C1(_115_),
    .C2(_079_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__a21oi_1 _165_ (
    .A1(_118_),
    .A2(_119_),
    .B1(_095_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__nor3_1 _166_ (
    .A(_080_),
    .B(_081_),
    .C(_112_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__o21a_1 _167_ (
    .A1(_080_),
    .A2(_112_),
    .B1(_081_),
    .X(_121_)
  );
  sky130_fd_sc_hd__nor2_1 _168_ (
    .A(_120_),
    .B(_121_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__a22o_1 _169_ (
    .A1(_080_),
    .A2(_115_),
    .B1(_117_),
    .B2(_108_),
    .X(_123_)
  );
  sky130_fd_sc_hd__a221oi_1 _170_ (
    .A1(_081_),
    .A2(_099_),
    .B1(_102_),
    .B2(_122_),
    .C1(_123_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__nor2_1 _171_ (
    .A(_095_),
    .B(_124_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__nor4_1 _172_ (
    .A(_080_),
    .B(_081_),
    .C(_082_),
    .D(_112_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__xnor2_1 _173_ (
    .A(_082_),
    .B(_120_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__a21oi_1 _174_ (
    .A1(_094_),
    .A2(_097_),
    .B1(_084_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__a221oi_1 _175_ (
    .A1(_108_),
    .A2(_122_),
    .B1(_126_),
    .B2(_102_),
    .C1(_127_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__nor3_1 _176_ (
    .A(_084_),
    .B(_094_),
    .C(_082_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__nor3_1 _177_ (
    .A(_095_),
    .B(_128_),
    .C(_129_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__xnor2_1 _178_ (
    .A(_083_),
    .B(_125_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__nand2_1 _179_ (
    .A(_102_),
    .B(_130_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__nand2_1 _180_ (
    .A(_083_),
    .B(_099_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__a22oi_1 _181_ (
    .A1(_082_),
    .A2(_115_),
    .B1(_126_),
    .B2(_108_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__a31oi_1 _182_ (
    .A1(_131_),
    .A2(_132_),
    .A3(_133_),
    .B1(_095_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nand3b_1 _183_ (
    .A_N(_125_),
    .B(_108_),
    .C(_083_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__nor2_1 _184_ (
    .A(_095_),
    .B(_099_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__o211ai_1 _185_ (
    .A1(_084_),
    .A2(_083_),
    .B1(_134_),
    .C1(_135_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__a21oi_1 _186_ (
    .A1(_098_),
    .A2(_125_),
    .B1(_136_),
    .Y(_093_)
  );
  assign sel = { Shift, Negation };
  assign _095_ = Zero;
  assign _076_ = Multiplicant[0];
  assign _084_ = Negation;
  assign _094_ = Shift;
  assign Result[0] = _085_;
  assign _077_ = Multiplicant[1];
  assign Result[1] = _086_;
  assign _078_ = Multiplicant[2];
  assign Result[2] = _087_;
  assign _079_ = Multiplicant[3];
  assign Result[3] = _088_;
  assign _080_ = Multiplicant[4];
  assign Result[4] = _089_;
  assign _081_ = Multiplicant[5];
  assign Result[5] = _090_;
  assign _082_ = Multiplicant[6];
  assign Result[6] = _091_;
  assign _083_ = Multiplicant[7];
  assign Result[7] = _092_;
  assign Result[8] = _093_;
endmodule
