/* Generated by Yosys 0.42+2 (git sha1 82783646e, g++ 13.2.0-23ubuntu4 -fPIC -Os) */

module Multiplier_Sub_Module(Multiplicant, Inv_Multiplicant, Shift, Negation, Zero, Result);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _50_;
  input [3:0] Inv_Multiplicant;
  wire [3:0] Inv_Multiplicant;
  input [3:0] Multiplicant;
  wire [3:0] Multiplicant;
  input Negation;
  wire Negation;
  output [4:0] Result;
  wire [4:0] Result;
  input Shift;
  wire Shift;
  input Zero;
  wire Zero;
  wire [1:0] sel;
  sky130_fd_sc_hd__nand3b_1 _51_ (
    .A_N(_42_),
    .B(_28_),
    .C(_36_),
    .Y(_44_)
  );
  sky130_fd_sc_hd__or3b_1 _52_ (
    .A(_36_),
    .B(_42_),
    .C_N(_32_),
    .X(_45_)
  );
  sky130_fd_sc_hd__a21oi_1 _53_ (
    .A1(_44_),
    .A2(_45_),
    .B1(_43_),
    .Y(_37_)
  );
  sky130_fd_sc_hd__mux4_2 _54_ (
    .A0(_33_),
    .A1(_29_),
    .A2(_32_),
    .A3(_28_),
    .S0(_36_),
    .S1(_42_),
    .X(_46_)
  );
  sky130_fd_sc_hd__nor2b_1 _55_ (
    .A(_43_),
    .B_N(_46_),
    .Y(_38_)
  );
  sky130_fd_sc_hd__mux4_2 _56_ (
    .A0(_34_),
    .A1(_30_),
    .A2(_33_),
    .A3(_29_),
    .S0(_36_),
    .S1(_42_),
    .X(_47_)
  );
  sky130_fd_sc_hd__nor2b_1 _57_ (
    .A(_43_),
    .B_N(_47_),
    .Y(_39_)
  );
  sky130_fd_sc_hd__mux4_2 _58_ (
    .A0(_35_),
    .A1(_31_),
    .A2(_34_),
    .A3(_30_),
    .S0(_36_),
    .S1(_42_),
    .X(_48_)
  );
  sky130_fd_sc_hd__nor2b_1 _59_ (
    .A(_43_),
    .B_N(_48_),
    .Y(_40_)
  );
  sky130_fd_sc_hd__nand3_1 _60_ (
    .A(_36_),
    .B(_42_),
    .C(_31_),
    .Y(_49_)
  );
  sky130_fd_sc_hd__nand3b_1 _61_ (
    .A_N(_36_),
    .B(_42_),
    .C(_35_),
    .Y(_50_)
  );
  sky130_fd_sc_hd__a21oi_1 _62_ (
    .A1(_49_),
    .A2(_50_),
    .B1(_43_),
    .Y(_41_)
  );
  assign sel = { Shift, Negation };
  assign _36_ = Negation;
  assign _42_ = Shift;
  assign _28_ = Inv_Multiplicant[0];
  assign _32_ = Multiplicant[0];
  assign _43_ = Zero;
  assign Result[0] = _37_;
  assign _29_ = Inv_Multiplicant[1];
  assign _33_ = Multiplicant[1];
  assign Result[1] = _38_;
  assign _30_ = Inv_Multiplicant[2];
  assign _34_ = Multiplicant[2];
  assign Result[2] = _39_;
  assign _31_ = Inv_Multiplicant[3];
  assign _35_ = Multiplicant[3];
  assign Result[3] = _40_;
  assign Result[4] = _41_;
endmodule
