/* Generated by Yosys 0.42+2 (git sha1 82783646e, g++ 13.2.0-23ubuntu4 -fPIC -Os) */

module Multiplier_Sub_Module(Multiplicant, Shift, Negation, Zero, Result);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _50_;
  wire _51_;
  wire _52_;
  wire _53_;
  wire _54_;
  wire _55_;
  wire _56_;
  wire _57_;
  wire _58_;
  wire _59_;
  wire _60_;
  wire _61_;
  wire _62_;
  wire _63_;
  wire _64_;
  wire _65_;
  wire _66_;
  wire _67_;
  wire _68_;
  wire _69_;
  wire _70_;
  input [3:0] Multiplicant;
  wire [3:0] Multiplicant;
  input Negation;
  wire Negation;
  output [4:0] Result;
  wire [4:0] Result;
  input Shift;
  wire Shift;
  input Zero;
  wire Zero;
  wire [1:0] sel;
  sky130_fd_sc_hd__nor3b_1 _71_ (
    .A(_50_),
    .B(_49_),
    .C_N(_39_),
    .Y(_44_)
  );
  sky130_fd_sc_hd__nand2b_1 _72_ (
    .A_N(_49_),
    .B(_40_),
    .Y(_51_)
  );
  sky130_fd_sc_hd__nor2_1 _73_ (
    .A(_43_),
    .B(_49_),
    .Y(_52_)
  );
  sky130_fd_sc_hd__o21ai_0 _74_ (
    .A1(_43_),
    .A2(_49_),
    .B1(_39_),
    .Y(_53_)
  );
  sky130_fd_sc_hd__nor2b_1 _75_ (
    .A(_49_),
    .B_N(_43_),
    .Y(_54_)
  );
  sky130_fd_sc_hd__xnor2_1 _76_ (
    .A(_51_),
    .B(_53_),
    .Y(_55_)
  );
  sky130_fd_sc_hd__nor2_1 _77_ (
    .A(_50_),
    .B(_55_),
    .Y(_45_)
  );
  sky130_fd_sc_hd__or3_1 _78_ (
    .A(_39_),
    .B(_40_),
    .C(_41_),
    .X(_56_)
  );
  sky130_fd_sc_hd__o21ai_0 _79_ (
    .A1(_39_),
    .A2(_40_),
    .B1(_41_),
    .Y(_57_)
  );
  sky130_fd_sc_hd__nand3_1 _80_ (
    .A(_54_),
    .B(_56_),
    .C(_57_),
    .Y(_58_)
  );
  sky130_fd_sc_hd__xor2_1 _81_ (
    .A(_39_),
    .B(_40_),
    .X(_59_)
  );
  sky130_fd_sc_hd__nand3_1 _82_ (
    .A(_43_),
    .B(_49_),
    .C(_59_),
    .Y(_60_)
  );
  sky130_fd_sc_hd__nor2b_1 _83_ (
    .A(_43_),
    .B_N(_49_),
    .Y(_61_)
  );
  sky130_fd_sc_hd__a22oi_1 _84_ (
    .A1(_41_),
    .A2(_52_),
    .B1(_61_),
    .B2(_40_),
    .Y(_62_)
  );
  sky130_fd_sc_hd__a31oi_1 _85_ (
    .A1(_58_),
    .A2(_60_),
    .A3(_62_),
    .B1(_50_),
    .Y(_46_)
  );
  sky130_fd_sc_hd__or4_1 _86_ (
    .A(_39_),
    .B(_40_),
    .C(_41_),
    .D(_42_),
    .X(_63_)
  );
  sky130_fd_sc_hd__o31ai_1 _87_ (
    .A1(_39_),
    .A2(_40_),
    .A3(_41_),
    .B1(_42_),
    .Y(_64_)
  );
  sky130_fd_sc_hd__nand3_1 _88_ (
    .A(_54_),
    .B(_63_),
    .C(_64_),
    .Y(_65_)
  );
  sky130_fd_sc_hd__nand4_1 _89_ (
    .A(_43_),
    .B(_49_),
    .C(_56_),
    .D(_57_),
    .Y(_66_)
  );
  sky130_fd_sc_hd__a22oi_1 _90_ (
    .A1(_42_),
    .A2(_52_),
    .B1(_61_),
    .B2(_41_),
    .Y(_67_)
  );
  sky130_fd_sc_hd__a31oi_1 _91_ (
    .A1(_65_),
    .A2(_66_),
    .A3(_67_),
    .B1(_50_),
    .Y(_47_)
  );
  sky130_fd_sc_hd__nand4_1 _92_ (
    .A(_43_),
    .B(_49_),
    .C(_42_),
    .D(_56_),
    .Y(_68_)
  );
  sky130_fd_sc_hd__nor2_1 _93_ (
    .A(_43_),
    .B(_42_),
    .Y(_69_)
  );
  sky130_fd_sc_hd__nor3_1 _94_ (
    .A(_50_),
    .B(_52_),
    .C(_69_),
    .Y(_70_)
  );
  sky130_fd_sc_hd__and3_1 _95_ (
    .A(_63_),
    .B(_68_),
    .C(_70_),
    .X(_48_)
  );
  assign sel = { Shift, Negation };
  assign _50_ = Zero;
  assign _39_ = Multiplicant[0];
  assign _43_ = Negation;
  assign _49_ = Shift;
  assign Result[0] = _44_;
  assign _40_ = Multiplicant[1];
  assign Result[1] = _45_;
  assign _41_ = Multiplicant[2];
  assign Result[2] = _46_;
  assign _42_ = Multiplicant[3];
  assign Result[3] = _47_;
  assign Result[4] = _48_;
endmodule
