/* Generated by Yosys 0.42+2 (git sha1 82783646e, g++ 13.2.0-23ubuntu4 -fPIC -Os) */

module Multiplier_Sub_Module(Multiplicant, Shift, Negation, Zero, Result);
  wire [4:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _50_;
  wire _51_;
  wire _52_;
  wire _53_;
  input [3:0] Multiplicant;
  wire [3:0] Multiplicant;
  input Negation;
  wire Negation;
  output [4:0] Result;
  reg [4:0] Result = 5'h00;
  input Shift;
  wire Shift;
  input Zero;
  wire Zero;
  sky130_fd_sc_hd__xnor2_1 _54_ (
    .A(_37_),
    .B(_41_),
    .Y(_45_)
  );
  sky130_fd_sc_hd__nor3_1 _55_ (
    .A(_43_),
    .B(_42_),
    .C(_45_),
    .Y(_32_)
  );
  sky130_fd_sc_hd__mux2_1 _56_ (
    .A0(_38_),
    .A1(_37_),
    .S(_42_),
    .X(_46_)
  );
  sky130_fd_sc_hd__o21bai_1 _57_ (
    .A1(_41_),
    .A2(_46_),
    .B1_N(_43_),
    .Y(_47_)
  );
  sky130_fd_sc_hd__a21oi_1 _58_ (
    .A1(_41_),
    .A2(_46_),
    .B1(_47_),
    .Y(_33_)
  );
  sky130_fd_sc_hd__mux2_1 _59_ (
    .A0(_39_),
    .A1(_38_),
    .S(_42_),
    .X(_48_)
  );
  sky130_fd_sc_hd__o21bai_1 _60_ (
    .A1(_41_),
    .A2(_48_),
    .B1_N(_43_),
    .Y(_49_)
  );
  sky130_fd_sc_hd__a21oi_1 _61_ (
    .A1(_41_),
    .A2(_48_),
    .B1(_49_),
    .Y(_34_)
  );
  sky130_fd_sc_hd__mux2_1 _62_ (
    .A0(_40_),
    .A1(_39_),
    .S(_42_),
    .X(_50_)
  );
  sky130_fd_sc_hd__o21bai_1 _63_ (
    .A1(_41_),
    .A2(_50_),
    .B1_N(_43_),
    .Y(_51_)
  );
  sky130_fd_sc_hd__a21oi_1 _64_ (
    .A1(_41_),
    .A2(_50_),
    .B1(_51_),
    .Y(_35_)
  );
  sky130_fd_sc_hd__a21oi_1 _65_ (
    .A1(_42_),
    .A2(_40_),
    .B1(_41_),
    .Y(_52_)
  );
  sky130_fd_sc_hd__and3_1 _66_ (
    .A(_42_),
    .B(_41_),
    .C(_40_),
    .X(_53_)
  );
  sky130_fd_sc_hd__nor3_1 _67_ (
    .A(_43_),
    .B(_52_),
    .C(_53_),
    .Y(_36_)
  );
  always @*
    if (!_01_) Result[0] = _00_[0];
  always @*
    if (!_01_) Result[1] = _00_[1];
  always @*
    if (!_01_) Result[2] = _00_[2];
  always @*
    if (!_01_) Result[3] = _00_[3];
  always @*
    if (!_01_) Result[4] = _00_[4];
  assign _44_ = 1'h0;
  assign _43_ = Zero;
  assign _37_ = Multiplicant[0];
  assign _42_ = Shift;
  assign _41_ = Negation;
  assign _00_[0] = _32_;
  assign _38_ = Multiplicant[1];
  assign _00_[1] = _33_;
  assign _39_ = Multiplicant[2];
  assign _00_[2] = _34_;
  assign _40_ = Multiplicant[3];
  assign _00_[3] = _35_;
  assign _00_[4] = _36_;
  assign _01_ = _44_;
endmodule
