/* Generated by Yosys 0.42+2 (git sha1 82783646e, g++ 13.2.0-23ubuntu4 -fPIC -Os) */

module Multiplier_4X4(Multiplicant, Shift, Negation, Zero, Result);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _50_;
  wire _51_;
  wire _52_;
  wire _53_;
  wire _54_;
  wire _55_;
  input [3:0] Multiplicant;
  wire [3:0] Multiplicant;
  input Negation;
  wire Negation;
  output [4:0] Result;
  wire [4:0] Result;
  input Shift;
  wire Shift;
  input Zero;
  wire Zero;
  wire [1:0] sel;
  sky130_fd_sc_hd__nor2_1 _56_ (
    .A(_45_),
    .B(_44_),
    .Y(_46_)
  );
  sky130_fd_sc_hd__o21ai_0 _57_ (
    .A1(_34_),
    .A2(_38_),
    .B1(_46_),
    .Y(_47_)
  );
  sky130_fd_sc_hd__a21oi_1 _58_ (
    .A1(_34_),
    .A2(_38_),
    .B1(_47_),
    .Y(_39_)
  );
  sky130_fd_sc_hd__mux2_1 _59_ (
    .A0(_35_),
    .A1(_34_),
    .S(_44_),
    .X(_48_)
  );
  sky130_fd_sc_hd__o21bai_1 _60_ (
    .A1(_38_),
    .A2(_48_),
    .B1_N(_45_),
    .Y(_49_)
  );
  sky130_fd_sc_hd__a21oi_1 _61_ (
    .A1(_38_),
    .A2(_48_),
    .B1(_49_),
    .Y(_40_)
  );
  sky130_fd_sc_hd__mux2_1 _62_ (
    .A0(_36_),
    .A1(_35_),
    .S(_44_),
    .X(_50_)
  );
  sky130_fd_sc_hd__o21bai_1 _63_ (
    .A1(_38_),
    .A2(_50_),
    .B1_N(_45_),
    .Y(_51_)
  );
  sky130_fd_sc_hd__a21oi_1 _64_ (
    .A1(_38_),
    .A2(_50_),
    .B1(_51_),
    .Y(_41_)
  );
  sky130_fd_sc_hd__mux2_1 _65_ (
    .A0(_37_),
    .A1(_36_),
    .S(_44_),
    .X(_52_)
  );
  sky130_fd_sc_hd__o21bai_1 _66_ (
    .A1(_38_),
    .A2(_52_),
    .B1_N(_45_),
    .Y(_53_)
  );
  sky130_fd_sc_hd__a21oi_1 _67_ (
    .A1(_38_),
    .A2(_52_),
    .B1(_53_),
    .Y(_42_)
  );
  sky130_fd_sc_hd__a21oi_1 _68_ (
    .A1(_44_),
    .A2(_37_),
    .B1(_38_),
    .Y(_54_)
  );
  sky130_fd_sc_hd__and3_1 _69_ (
    .A(_38_),
    .B(_44_),
    .C(_37_),
    .X(_55_)
  );
  sky130_fd_sc_hd__nor3_1 _70_ (
    .A(_45_),
    .B(_54_),
    .C(_55_),
    .Y(_43_)
  );
  assign sel = { Shift, Negation };
  assign _45_ = Zero;
  assign _34_ = Multiplicant[0];
  assign _38_ = Negation;
  assign _44_ = Shift;
  assign Result[0] = _39_;
  assign _35_ = Multiplicant[1];
  assign Result[1] = _40_;
  assign _36_ = Multiplicant[2];
  assign Result[2] = _41_;
  assign _37_ = Multiplicant[3];
  assign Result[3] = _42_;
  assign Result[4] = _43_;
endmodule
