/* Generated by Yosys 0.42+2 (git sha1 82783646e, g++ 13.2.0-23ubuntu4 -fPIC -Os) */

module Carry_Look_Ahead_Adder(A, B, S);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  input [4:0] A;
  wire [4:0] A;
  input [4:0] B;
  wire [4:0] B;
  wire [4:0] P;
  output [4:0] S;
  wire [4:0] S;
  sky130_fd_sc_hd__nand2_1 _48_ (
    .A(_28_),
    .B(_23_),
    .Y(_38_)
  );
  sky130_fd_sc_hd__xor2_1 _49_ (
    .A(_28_),
    .B(_23_),
    .X(_33_)
  );
  sky130_fd_sc_hd__nor2_1 _50_ (
    .A(_29_),
    .B(_24_),
    .Y(_39_)
  );
  sky130_fd_sc_hd__nand2_1 _51_ (
    .A(_29_),
    .B(_24_),
    .Y(_40_)
  );
  sky130_fd_sc_hd__nor2b_1 _52_ (
    .A(_39_),
    .B_N(_40_),
    .Y(_41_)
  );
  sky130_fd_sc_hd__xnor2_1 _53_ (
    .A(_38_),
    .B(_41_),
    .Y(_34_)
  );
  sky130_fd_sc_hd__o21ai_0 _54_ (
    .A1(_38_),
    .A2(_39_),
    .B1(_40_),
    .Y(_42_)
  );
  sky130_fd_sc_hd__xnor2_1 _55_ (
    .A(_30_),
    .B(_25_),
    .Y(_43_)
  );
  sky130_fd_sc_hd__xnor2_1 _56_ (
    .A(_42_),
    .B(_43_),
    .Y(_35_)
  );
  sky130_fd_sc_hd__maj3_1 _57_ (
    .A(_30_),
    .B(_25_),
    .C(_42_),
    .X(_44_)
  );
  sky130_fd_sc_hd__xnor2_1 _58_ (
    .A(_31_),
    .B(_26_),
    .Y(_45_)
  );
  sky130_fd_sc_hd__xnor2_1 _59_ (
    .A(_44_),
    .B(_45_),
    .Y(_36_)
  );
  sky130_fd_sc_hd__maj3_1 _60_ (
    .A(_31_),
    .B(_26_),
    .C(_44_),
    .X(_46_)
  );
  sky130_fd_sc_hd__xnor2_1 _61_ (
    .A(_32_),
    .B(_27_),
    .Y(_47_)
  );
  sky130_fd_sc_hd__xnor2_1 _62_ (
    .A(_46_),
    .B(_47_),
    .Y(_37_)
  );
  assign P[0] = S[0];
  assign _28_ = B[0];
  assign _23_ = A[0];
  assign S[0] = _33_;
  assign _29_ = B[1];
  assign _24_ = A[1];
  assign S[1] = _34_;
  assign _30_ = B[2];
  assign _25_ = A[2];
  assign S[2] = _35_;
  assign _31_ = B[3];
  assign _26_ = A[3];
  assign S[3] = _36_;
  assign _32_ = B[4];
  assign _27_ = A[4];
  assign S[4] = _37_;
endmodule

module Full_Adder(Sum, Cout, A, B, C);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  wire _5_;
  wire _6_;
  wire _7_;
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output Cout;
  wire Cout;
  output Sum;
  wire Sum;
  sky130_fd_sc_hd__xor3_1 _8_ (
    .A(_4_),
    .B(_3_),
    .C(_5_),
    .X(_7_)
  );
  sky130_fd_sc_hd__maj3_1 _9_ (
    .A(_4_),
    .B(_3_),
    .C(_5_),
    .X(_6_)
  );
  assign _4_ = B;
  assign _3_ = A;
  assign _5_ = C;
  assign Sum = _7_;
  assign Cout = _6_;
endmodule

module Half_Adder(Sum, Cout, A, B);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  input A;
  wire A;
  input B;
  wire B;
  output Cout;
  wire Cout;
  output Sum;
  wire Sum;
  sky130_fd_sc_hd__and2_0 _4_ (
    .A(_1_),
    .B(_0_),
    .X(_2_)
  );
  sky130_fd_sc_hd__xor2_1 _5_ (
    .A(_1_),
    .B(_0_),
    .X(_3_)
  );
  assign _1_ = B;
  assign _0_ = A;
  assign Sum = _3_;
  assign Cout = _2_;
endmodule

module Multiplier_4x4(Result, In_1, In_2, Sign);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire \And_array[0] ;
  wire \And_array[10] ;
  wire \And_array[11] ;
  wire \And_array[12] ;
  wire \And_array[13] ;
  wire \And_array[14] ;
  wire \And_array[15] ;
  wire \And_array[1] ;
  wire \And_array[2] ;
  wire \And_array[3] ;
  wire \And_array[4] ;
  wire \And_array[5] ;
  wire \And_array[6] ;
  wire \And_array[7] ;
  wire \And_array[8] ;
  wire \And_array[9] ;
  wire [5:0] Carry_1;
  wire [4:0] Carry_2;
  wire Complement;
  input [3:0] In_1;
  wire [3:0] In_1;
  input [3:0] In_2;
  wire [3:0] In_2;
  output [7:0] Result;
  wire [7:0] Result;
  input Sign;
  wire Sign;
  wire [4:0] Sum_1;
  wire [3:0] Sum_2;
  wire [4:0] Sum_Sign;
  sky130_fd_sc_hd__mux2_1 _38_ (
    .A0(_31_),
    .A1(_26_),
    .S(_30_),
    .X(_06_)
  );
  sky130_fd_sc_hd__and2_0 _39_ (
    .A(_31_),
    .B(_30_),
    .X(_22_)
  );
  sky130_fd_sc_hd__and2_0 _40_ (
    .A(_27_),
    .B(_23_),
    .X(_12_)
  );
  sky130_fd_sc_hd__and2_0 _41_ (
    .A(_23_),
    .B(_28_),
    .X(_11_)
  );
  sky130_fd_sc_hd__and2_0 _42_ (
    .A(_23_),
    .B(_29_),
    .X(_10_)
  );
  sky130_fd_sc_hd__and2_0 _43_ (
    .A(_27_),
    .B(_24_),
    .X(_08_)
  );
  sky130_fd_sc_hd__and2_0 _44_ (
    .A(_28_),
    .B(_24_),
    .X(_07_)
  );
  sky130_fd_sc_hd__and2_0 _45_ (
    .A(_29_),
    .B(_24_),
    .X(_21_)
  );
  sky130_fd_sc_hd__and2_0 _46_ (
    .A(_27_),
    .B(_25_),
    .X(_19_)
  );
  sky130_fd_sc_hd__and2_0 _47_ (
    .A(_28_),
    .B(_25_),
    .X(_18_)
  );
  sky130_fd_sc_hd__and2_0 _48_ (
    .A(_29_),
    .B(_25_),
    .X(_17_)
  );
  sky130_fd_sc_hd__o21ai_0 _49_ (
    .A1(_31_),
    .A2(_23_),
    .B1(_30_),
    .Y(_32_)
  );
  sky130_fd_sc_hd__a21oi_1 _50_ (
    .A1(_31_),
    .A2(_23_),
    .B1(_32_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__o21ai_0 _51_ (
    .A1(_31_),
    .A2(_24_),
    .B1(_30_),
    .Y(_33_)
  );
  sky130_fd_sc_hd__a21oi_1 _52_ (
    .A1(_31_),
    .A2(_24_),
    .B1(_33_),
    .Y(_20_)
  );
  sky130_fd_sc_hd__o21ai_0 _53_ (
    .A1(_31_),
    .A2(_25_),
    .B1(_30_),
    .Y(_34_)
  );
  sky130_fd_sc_hd__a21oi_1 _54_ (
    .A1(_31_),
    .A2(_25_),
    .B1(_34_),
    .Y(_16_)
  );
  sky130_fd_sc_hd__nand2_1 _55_ (
    .A(_26_),
    .B(_27_),
    .Y(_35_)
  );
  sky130_fd_sc_hd__xnor2_1 _56_ (
    .A(_31_),
    .B(_35_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__nand2_1 _57_ (
    .A(_26_),
    .B(_28_),
    .Y(_36_)
  );
  sky130_fd_sc_hd__xnor2_1 _58_ (
    .A(_31_),
    .B(_36_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__nand2_1 _59_ (
    .A(_26_),
    .B(_29_),
    .Y(_37_)
  );
  sky130_fd_sc_hd__xnor2_1 _60_ (
    .A(_31_),
    .B(_37_),
    .Y(_13_)
  );
  Carry_Look_Ahead_Adder CLA (
    .A({ Sign, Sum_Sign[3], Sum_2[2:0] }),
    .B(Carry_2),
    .S(Result[7:3])
  );
  Full_Adder Fa_10 (
    .A(\And_array[7] ),
    .B(\And_array[10] ),
    .C(\And_array[13] ),
    .Cout(Carry_1[1]),
    .Sum(Sum_1[0])
  );
  Full_Adder Fa_11 (
    .A(\And_array[3] ),
    .B(\And_array[6] ),
    .C(Sign),
    .Cout(Carry_1[2]),
    .Sum(Sum_1[1])
  );
  Full_Adder Fa_12 (
    .A(\And_array[9] ),
    .B(\And_array[12] ),
    .C(Complement),
    .Cout(Carry_1[3]),
    .Sum(Sum_1[2])
  );
  Full_Adder Fa_13 (
    .A(\And_array[2] ),
    .B(\And_array[5] ),
    .C(\And_array[8] ),
    .Cout(Carry_1[4]),
    .Sum(Sum_1[3])
  );
  Full_Adder Fa_20 (
    .A(Carry_1[1]),
    .B(Sum_1[1]),
    .C(Sum_1[2]),
    .Cout(Carry_2[1]),
    .Sum(Sum_2[0])
  );
  Full_Adder Fa_21 (
    .A(Carry_1[2]),
    .B(Carry_1[3]),
    .C(Sum_1[3]),
    .Cout(Carry_2[2]),
    .Sum(Sum_2[1])
  );
  Half_Adder Ha_10 (
    .A(\And_array[11] ),
    .B(\And_array[14] ),
    .Cout(Carry_1[0]),
    .Sum(Result[1])
  );
  Half_Adder Ha_11 (
    .A(\And_array[1] ),
    .B(\And_array[4] ),
    .Cout(Carry_1[5]),
    .Sum(Sum_1[4])
  );
  Half_Adder Ha_20 (
    .A(Carry_1[0]),
    .B(Sum_1[0]),
    .Cout(Carry_2[0]),
    .Sum(Result[2])
  );
  Half_Adder Ha_21 (
    .A(Carry_1[4]),
    .B(Sum_1[4]),
    .Cout(Carry_2[3]),
    .Sum(Sum_2[2])
  );
  Half_Adder Ha_22 (
    .A(Carry_1[5]),
    .B(\And_array[0] ),
    .Cout(Carry_2[4]),
    .Sum(Sum_Sign[3])
  );
  assign Result[0] = \And_array[15] ;
  assign Sum_2[3] = Sum_Sign[3];
  assign { Sum_Sign[4], Sum_Sign[2:0] } = { Sign, Sum_2[2:0] };
  assign _31_ = Sign;
  assign _26_ = In_1[3];
  assign _30_ = In_2[3];
  assign \And_array[0]  = _06_;
  assign Complement = _22_;
  assign _27_ = In_2[0];
  assign _23_ = In_1[0];
  assign \And_array[15]  = _12_;
  assign _28_ = In_2[1];
  assign \And_array[14]  = _11_;
  assign _29_ = In_2[2];
  assign \And_array[13]  = _10_;
  assign _24_ = In_1[1];
  assign \And_array[11]  = _08_;
  assign \And_array[10]  = _07_;
  assign \And_array[9]  = _21_;
  assign _25_ = In_1[2];
  assign \And_array[7]  = _19_;
  assign \And_array[6]  = _18_;
  assign \And_array[5]  = _17_;
  assign \And_array[12]  = _09_;
  assign \And_array[8]  = _20_;
  assign \And_array[4]  = _16_;
  assign \And_array[3]  = _15_;
  assign \And_array[2]  = _14_;
  assign \And_array[1]  = _13_;
endmodule
